<a href="https://colab.research.google.com/github/JADASIMONESIMON/-Hooplytics-complex-messy-data-project/blob/main/notebooks/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#import tools
import requests
import pandas as pd

In [3]:
#API Key
API_KEY = "11f847a9-8965-4f08-8239-98b98e34e2f8"

In [4]:
#calling API Key
url = "https://api.balldontlie.io/v1/players"  # go back to this for now

headers = {
    "Authorization": API_KEY
}

params = {
    "season": 2024,
    "season_type": "regular",
    "type": "base",
    "per_page": 100
}

In [11]:
response = requests.get(url, headers=headers, params=params)

print("Status:", response.status_code)
print("Text preview:", response.text[:300])

data = response.json()
df_2024 = pd.json_normalize(data["data"])
df_2024.head()

Status: 200
Text preview: {"data":[{"id":1,"first_name":"Alex","last_name":"Abrines","position":"G","height":"6-6","weight":"190","jersey_number":"8","college":"FC Barcelona","country":"Spain","draft_year":2013,"draft_round":2,"draft_number":32,"team":{"id":21,"conference":"West","division":"Northwest","city":"Oklahoma City"

,id,first_name,last_name,position,height,weight,jersey_number,college,country,draft_year,draft_round,draft_number,team.id,team.conference,team.division,team.city,team.name,team.full_name,team.abbreviation
0,1,Alex,Abrines,G,6-6,190,8,FC Barcelona,Spain,2013.0,2.0,32.0,21,West,Northwest,Oklahoma City,Thunder,Oklahoma City Thunder,OKC
1,2,Jaylen,Adams,G,6-0,225,10,St. Bonaventure,USA,NaN,NaN,NaN,1,East,Southeast,Atlanta,Hawks,Atlanta Hawks,ATL
2,3,Steven,Adams,C,6-11,265,12,Pittsburgh,New Zealand,2013.0,1.0,12.0,11,West,Southwest,Houston,Rockets,Houston Rockets,HOU
3,4,Bam,Adebayo,C-F,6-9,255,13,Kentucky,USA,2017.0,1.0,14.0,16,East,Southeast,Miami,Heat,Miami Heat,MIA
4,5,DeVaughn,Akoon-Purcell,G-F,6-5,201,44,Illinois State,Trinidad and Tobago,2016.0,NaN,NaN,8,West,Northwest,Denver,Nuggets,Denver Nuggets,DEN

In [12]:
# TASK 1: Clean data (Avnoor)

# - Handle missing values
df_2024 = df_2024.fillna(0)

# - Convert columns to numeric
numeric_cols = ["height_feet", "height_inches", "weight_pounds"]
for col in numeric_cols:
    if col in df_2024.columns:
        df_2024[col] = pd.to_numeric(df_2024[col], errors='coerce')

# - Rename columns
df_2024 = df_2024.rename(columns={
    "first_name": "FirstName",
    "last_name": "LastName",
    "height_feet": "HeightFeet",
    "height_inches": "HeightInches",
    "weight_pounds": "Weight"
})

# - Remove bad rows (duplicates)
df_2024 = df_2024.drop_duplicates()

# Final output
df_2024.head()

,id,FirstName,LastName,position,height,weight,jersey_number,college,country,draft_year,draft_round,draft_number,team.id,team.conference,team.division,team.city,team.name,team.full_name,team.abbreviation
0,1,Alex,Abrines,G,6-6,190,8,FC Barcelona,Spain,2013.0,2.0,32.0,21,West,Northwest,Oklahoma City,Thunder,Oklahoma City Thunder,OKC
1,2,Jaylen,Adams,G,6-0,225,10,St. Bonaventure,USA,0.0,0.0,0.0,1,East,Southeast,Atlanta,Hawks,Atlanta Hawks,ATL
2,3,Steven,Adams,C,6-11,265,12,Pittsburgh,New Zealand,2013.0,1.0,12.0,11,West,Southwest,Houston,Rockets,Houston Rockets,HOU
3,4,Bam,Adebayo,C-F,6-9,255,13,Kentucky,USA,2017.0,1.0,14.0,16,East,Southeast,Miami,Heat,Miami Heat,MIA
4,5,DeVaughn,Akoon-Purcell,G-F,6-5,201,44,Illinois State,Trinidad and Tobago,2016.0,0.0,0.0,8,West,Northwest,Denver,Nuggets,Denver Nuggets,DEN

In [ ]:
# TASK 2: Feature Engineering
# - Calculate % of 3PT shots
# - Calculate % of 2PT shots
# - Create total shots column
# - (Optional) Group by season

In [ ]:
# TASK 3: Analysis
# - Sum league totals
# - Calculate overall percentages
# - Compare 3PT vs 2PT
# - Loop through multiple seasons

In [ ]:
#TASK 4 ; visualiztion + presentation
# - Bar chart (3PT vs 2PT)
# - Trend line over time
# - Clean notebook layout
# - Write explanation (IMPORTANT for grade)